apiVersion: v1
kind: ConfigMap
metadata:
  name: common-tracing-store
  namespace: prod
data:
  DB_HOST_RW: "tracing-store-prod.cluster-c72y6ow0q54b.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "tracing-store-prod.cluster-ro-c72y6ow0q54b.eu-south-1.rds.amazonaws.com"
  DB_NAME: "tracing_store"
  DB_PORT: "5432"
  DB_USE_SSL: "true"
