name: "tracing-be-api"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/tracing-be-api-{{.Values.namespace}}"

service:
  create: true
  portName: http
  containerPort: 8080
  targetGroupArn: ""
  targetType: "ip"
  ipAddressType: "ipv4"

configmap:
  ACCEPTED_AUDIENCES: "interop.pagopa.it/m2m"
  APPLICATION_NAME: "tracing-api"
  API_OPERATIONS_BASEURL: "http://tracing-be-operations.{{.Values.namespace}}:8080"
  S3_BUCKET_NAME: "tracing-files-{{.Values.namespace}}"
  STORAGE_PATH_NAME: "/tmp"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: 8080
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
  livenessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
  readinessProbe:
    httpGet:
      path: "/status"
      port: http
    periodSeconds: 5
    initialDelaySeconds: 15
