name: "tracing-be-enriched-data-handler"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/tracing-be-enriched-data-handler-{{.Values.namespace}}"

service:
  create: false

configmap:
  DB_SCHEMA_NAME: "{{.Values.namespace}}_traces"
  APPLICATION_NAME: "tracing-enriched-data-handler"
  SQS_ENRICHED_UPLOAD_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/{{.Values.local.awsAccountId}}/tracing-enriched-upload-{{.Values.namespace}}"
  SQS_ENRICHER_STATE_ENDPOINT: "https://sqs.eu-south-1.amazonaws.com/{{.Values.local.awsAccountId}}/tracing-enricher-state-{{.Values.namespace}}"
  S3_ENRICHED_BUCKET_NAME: "tracing-enriched-files-{{.Values.namespace}}"
  CONSUMER_POLLING_TIMEOUT_IN_SECONDS: "10"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "common-flyway-traces-schema"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "{{.Values.namespace}}"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_SCHEMAS: "{{.Values.namespace}}_traces"
    envFromConfigmaps:
      POSTGRES_HOST: "common-tracing-store.DB_HOST_RW"
      POSTGRES_PORT: "common-tracing-store.DB_PORT"
      POSTGRES_DB: "common-tracing-store.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "tracing-store-flyway-user.username"
      FLYWAY_PASSWORD: "tracing-store-flyway-user.password"

  envFromConfigmaps:
    DB_HOST: "common-tracing-store.DB_HOST_RW"
    DB_NAME: "common-tracing-store.DB_NAME"
    DB_PORT: "common-tracing-store.DB_PORT"
    DB_USE_SSL: "common-tracing-store.DB_USE_SSL"
  envFromSecrets:
    DB_USERNAME: "tracing-store-enriched-data-handler-user.username"
    DB_PASSWORD: "tracing-store-enriched-data-handler-user.password"
